### ISSUE TITLE
issue with mujoco

### ISSUE THREAD

**Issue by poutine-dejeuner** [arlo-lib/ARLO#1]
Getting this error when running the examples. I tried the fix suggested in the readme but the file to remove is absent from the folder. I will post an issue to the github of mujoco-py but figured it might be faster with you.

```
running build_ext
building 'mujoco_py.cymj' extension
gcc -pthread -B /home/vincent/anaconda3/envs/arlo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py -I/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/binaries/linux/mujoco210/include -I/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/numpy/core/include -I/home/vincent/anaconda3/envs/arlo/include/python3.8 -c /home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/cymj.c -o /home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.13_38_linuxcpuextensionbuilder/temp.linux-x86_64-3.8/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/cymj.o -fopenmp -w
gcc -pthread -B /home/vincent/anaconda3/envs/arlo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py -I/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/binaries/linux/mujoco210/include -I/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/numpy/core/include -I/home/vincent/anaconda3/envs/arlo/include/python3.8 -c /home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/gl/osmesashim.c -o /home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.13_38_linuxcpuextensionbuilder/temp.linux-x86_64-3.8/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/gl/osmesashim.o -fopenmp -w
/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/gl/osmesashim.c:1:10: fatal error: GL/osmesa.h: No such file or directory
    1 | #include <GL/osmesa.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/unixccompiler.py", line 117, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extract_dataset_from_env.py", line 1, in <module>
    from ARLO.block import DataGenerationRandomUniformPolicy
  File "/home/vincent/repos/ARLO/ARLO/__init__.py", line 1, in <module>
    from ARLO import(abstract_unit,
  File "/home/vincent/repos/ARLO/ARLO/block/__init__.py", line 1, in <module>
    from ARLO.block.block import *
  File "/home/vincent/repos/ARLO/ARLO/block/block.py", line 10, in <module>
    from mushroom_rl.utils.spaces import Discrete, Box
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mushroom_rl/utils/spaces.py", line 3, in <module>
    from mushroom_rl.core import Serializable
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mushroom_rl/core/__init__.py", line 7, in <module>
    import mushroom_rl.environments
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mushroom_rl/environments/__init__.py", line 24, in <module>
    from .mujoco import MuJoCo
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mushroom_rl/environments/mujoco.py", line 1, in <module>
    import mujoco_py
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/__init__.py", line 15, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/builder.py", line 499, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/builder.py", line 221, in build
    built_so_file_path = self._build_impl()
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/builder.py", line 273, in _build_impl
    so_file_path = super()._build_impl()
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/builder.py", line 244, in _build_impl
    dist.run_commands()
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/mujoco_py/builder.py", line 144, in build_extensions
    build_ext.build_extensions(self)
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/vincent/anaconda3/envs/arlo/lib/python3.8/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

```

**Comment by arloreinforcement** [comment]
Hi, 

Your problem is most likely related to a common issue regarding the installation of MuJoCo. If you look at the first error that arises you will see that it is the following: `fatal error: GL/osmesa.h: No such file or directory`

This happens when you don't have all the packages installed needed to use MuJoCo. A fix for this is detailed in the README of mujoco-py: [https://github.com/openai/mujoco-py#ubuntu-installtion-troubleshooting
](https://github.com/openai/mujoco-py#ubuntu-installtion-troubleshooting
)

Namely, you must run the following: `sudo apt install libosmesa6-dev libgl1-mesa-glx libglfw3`

Hopefully this solves your issue, in any case this is simply an issue with the installation of MuJoCo and it is not related with ARLO.

Please note that the fix mentioned in the README of ARLO is not related to this problem, so you should revert any changes you made, as it is a fix related to other issues. 
On this note, but this is unrelated to your issue, what do you mean when you say that "the file to remove is absent from the folder"? Did you download the MuJoCo binaries?
